version: '3'

services:
  influxdb:
    image: influxdb:latest
    hostname: "influxdb"
    ports:
    - "8086:8086"
    env_file:
    - .env
    volumes:
    - "$PWD/influxdb:/var/lib/influxdb"
    networks:
    - hovel-latency

  grafana:
    image: "grafana/grafana:latest"
    hostname: "grafana"
    networks:
    - hovel-latency
    env_file:
    - .env
    ports:
    - "3000:3000"
    volumes:
    - "./config/grafana/provisioning:/etc/grafana/provisioning"

  telegraf:
    image: "telegraf:1.16"
    hostname: "telegraf"
    networks:
    - hovel-latency
    env_file:
    - .env
    volumes:
    - "./config/telegraf:/etc/telegraf"
    - "./config/entrypoint_telegraf.sh:/entrypoint.sh"

  speedtest:
    container_name: speedtest
    build: .
    env_file:
    - .env
    networks:
    - hovel-latency


volumes:
  influxdb:


networks:
  hovel-latency:
    driver: bridge
